### ISSUE TITLE
Drizzt Saga- Regis says nothing

### ISSUE THREAD

**Issue by CavaliereITA73** [Black-Wyrm-Lair/Drizzt-Saga#29]
I have the most recent version of BGT standard installed (20.1), and I am ready to embark on drizzt saga. I FINISH DURLAG TOWER AND IN ULGOTH'S BREAD I have drizzt in my party, but I cannot go to 9 Hells or Icewind dale because in Ulgoth's Beard, Regis has nothing to say to me. I think I talked to Regis before drizzt joined, and that may have messed up the triggering mechanism. Is there a CLUAConsole global that I can set to trigger the Regis talk so I can go to 9 Hells and Icewind Dale? (I have installet RoT and One Drizzt mods.)

Thanks.

**Comment by Roberciiik** [comment]
Hello, that's unfortunate. I think it might be related to the One Drizzt mods as Regis expects you to have `F_DRIZZT` in your team, and If you have Drizzt in your team then it might be a different character file.

You can edit `f_regis` dialog logic in NearInfinity editor to not check the `F_DRIZZT` file then it should give you this quest. 

Could you please send Weidu.log here so potentially we could reproduce and fix the issue.

**Comment by CavaliereITA73** [comment]
[WeiDU.log](https://github.com/user-attachments/files/16134343/WeiDU.log)

**Comment by Roberciiik** [comment]
@CavaliereITA73 Let me know if that helped. We can try to find other solutions if not.

**Comment by CavaliereITA73** [comment]
Resolved
Thank you Roberciiiik!!!!!!

Thank you very much for helping!
Having also installed RoT and above all ONEDRIZZT I had to modify the f_regis file with NI
every time I found DRIZT2 with F_DRIZZT

**Comment by Roberciiik** [comment]
Glad to hear that. I will try to reproduce this in my spare time eventually. Thanks for the report.

**Comment by CavaliereITA73** [comment]
Good morning:
I have another problem..
I accept Drizzt at Uolght's Bread and notice that all his items are immovable. I accept it anyway and outside I find Regis who sends me to the nine hells. Except that every time I save and try to reload the game it crashes and the message appears: an assertion filed in CHVidlMAGE3d.Cpp at line number 899...

what can I do?

**Comment by Roberciiik** [comment]
@CavaliereITA73 

> I accept Drizzt at Uolght's Bread and notice that all his items are immovable.

It's the first time I heard that Drizzt items are immovable. It might be a safe hack for oBG2, as on BG:EE it works fine. On the other hand, as you are using One Drizzt mod, and probably a new character file is used for the "One Drizzt", then maybe his items are set to be immovable. 

> Except that every time I save and try to reload the game it crashes and the message appears: an assertion filed in CHVidlMAGE3d.Cpp at line number 899...

Can you do some tests on when it crashes? Is it only in nine hells? Or maybe it will fail after you finish this part of campaign too? Does it crash without Drizzt in the team? This crash could be or could not be related to Drizzt Saga at all. 

The other option is to ask on the SHS forum, as there might be someone who encountered this issue before. I am just guessing what could be wrong here.

**Comment by CavaliereITA73** [comment]
after i recruit drizzt it happens anytime. I think it has to do with his armor. if I take it off and put it back on, the image of drizzt appears. 

the game continues perfectly but as soon as I try to reload a saved game the game crashes.... 
From what I've read around, the problem arises when the game tries to load and doesn't "find" an image.

**Comment by CavaliereITA73** [comment]
It's Drizzt's armor. 
I tried to identify it and the game crashes.
I tried to remove it and the game crashes.
Even if I leave it without identifying it, the game still crashes...

**Comment by Roberciiik** [comment]
I installed latest Drizzt Saga, on BGT with fixpack and tobex. What I can see, only the armor and the off-hand sword cannot be removed. Armor is already identified. So I assume it is again related to "One Drizzt" mod that probably provided their own Drizzt file version with custom items that might or might not be faulty. What I can suggest is to find this drizzt file in the NearInfinity tool, check what is the armor item name, and then remove it completely from the game. You will need to provide some other armor to your character or so. If there is no animation, you can try to set it from NI as well. Hope this helps you a bit.

**Comment by CavaliereITA73** [comment]
that's what I imagine too. Except that ONE DRIZZT is essential if you also install RoT together...

I already tried with NI to change some values ​​of its armor but I didn't succeed..

which file should I open? under ITM or under CHR?

**Comment by CavaliereITA73** [comment]
I solved!!!!!

I looked for the chan02.itm file from another folder and put it in OVERRIDE.

Now everything works!!!!
Even if I don't see the image of drizzt and I can't take that damned armor off him.....

**Comment by Roberciiik** [comment]
> Except that ONE DRIZZT is essential if you also install RoT together...

I disagree. Without One Drizzt mod, in BG2 you would be encountered with a "new" Drizzt character, without your gear and experience from Drizzt Saga. It's not a big deal, TBH.

Good to hear that you were able to resolve this problem. You can try to change Drizzt animation by:
Open NI → from Save folder find your save game → find Drizzt NPC in the list → double-click to edit → go to Edit tab → Find CRE resource and then edit Animation value for FIGTHER_MALE_ELF for example.

**Comment by CavaliereITA73** [comment]
I'm sorry: are you absolutely certain of this? Are you sure I can install ROT EVEN WITHOUT One Drizzt Mod? That the only "inconvenience is having 2 Drizzts?".
So in the next mega installation I avoid all these problems by avoiding installing ONE drizzt MOD.....
Thank you!!

**Comment by Roberciiik** [comment]
Yes, I am pretty sure, that both mods will work fine separately in one EET/BGT installation. Because these modifications will add two different Drizzt characters files, and One Drizzt mod replaces them both with a single character file. You can ask on the forum are there any other disadvantages of that solution.

In BG2 part, you will simply encounter a "new" Drizzt NPC, without your BG1 DrizztSaga items, spells and experience.
