### ISSUE TITLE
how to reach winter wolf ritual

### ISSUE THREAD

**Issue by TotoR115** [Black-Wyrm-Lair/Drizzt-Saga#30]
See : https://forums.beamdog.com/discussion/88548/solved-question-drizzt-saga-how-to-reach-winter-wolf-ritual

With the component `access all new areas through worldmap` installed, it is not possible to go with the worldmap to the winter wolf ritual. I don't know if it is intended, but it looks strange as all other marker are accessible.

it may be good to add a link between Frost giant Hill and the Winter wolf ritual area.

**Comment by Roberciiik** [comment]
Fixed here and in BP-BGT-Worldmap
